export const dashboardStats = [
  {
    title: 'Active Projects',
    value: 12,
    trend: { value: 5, isPositive: true },
    icon: 'building',
  },
  {
    title: 'Team Members',
    value: 48,
    trend: { value: 3, isPositive: true },
    icon: 'users',
  },
  {
    title: 'Budget Remaining',
    value: '$485K',
    trend: { value: 12, isPositive: false },
    icon: 'wallet',
  },
  {
    title: 'Schedule Completion',
    value: '72%',
    trend: { value: 8, isPositive: true },
    icon: 'chart',
  },
];

export const projects = [
  {
    id: 1,
    name: 'Downtown Office Complex',
    location: 'New York, NY',
    status: 'In Progress',
    completion: 65,
    budget: '$2.5M',
    spent: '$1.6M',
    startDate: '2024-01-15',
    endDate: '2025-06-30',
  },
  {
    id: 2,
    name: 'Residential Tower A',
    location: 'Los Angeles, CA',
    status: 'In Progress',
    completion: 42,
    budget: '$5.2M',
    spent: '$2.2M',
    startDate: '2024-03-01',
    endDate: '2026-02-28',
  },
  {
    id: 3,
    name: 'Shopping Center Renovation',
    location: 'Chicago, IL',
    status: 'Planning',
    completion: 15,
    budget: '$1.8M',
    spent: '$270K',
    startDate: '2024-09-01',
    endDate: '2025-12-31',
  },
  {
    id: 4,
    name: 'Highway Expansion Project',
    location: 'Dallas, TX',
    status: 'Completed',
    completion: 100,
    budget: '$3.5M',
    spent: '$3.4M',
    startDate: '2023-06-01',
    endDate: '2024-11-15',
  },
  {
    id: 5,
    name: 'Hospital Wing Extension',
    location: 'Seattle, WA',
    status: 'In Progress',
    completion: 58,
    budget: '$4.1M',
    spent: '$2.4M',
    startDate: '2024-02-15',
    endDate: '2025-08-31',
  },
];

export const teamMembers = [
  {
    id: 1,
    name: 'John Doe',
    role: 'Project Manager',
    email: 'john.doe@smartsite.com',
    status: 'Active',
    projectsCount: 3,
  },
  {
    id: 2,
    name: 'Sarah Johnson',
    role: 'Site Supervisor',
    email: 'sarah.j@smartsite.com',
    status: 'Active',
    projectsCount: 2,
  },
  {
    id: 3,
    name: 'Mike Chen',
    role: 'Safety Officer',
    email: 'mike.chen@smartsite.com',
    status: 'Active',
    projectsCount: 5,
  },
  {
    id: 4,
    name: 'Emma Williams',
    role: 'Budget Analyst',
    email: 'emma.w@smartsite.com',
    status: 'Active',
    projectsCount: 4,
  },
  {
    id: 5,
    name: 'David Martinez',
    role: 'Architect',
    email: 'david.m@smartsite.com',
    status: 'Inactive',
    projectsCount: 2,
  },
];

export const alerts = [
  {
    id: 1,
    type: 'warning',
    title: 'Budget Overrun Alert',
    message: 'Downtown Office Complex is 15% over budget',
    date: '2024-01-20',
    read: false,
  },
  {
    id: 2,
    type: 'info',
    title: 'Schedule Update',
    message: 'Residential Tower A: Concrete pour completed on schedule',
    date: '2024-01-18',
    read: true,
  },
  {
    id: 3,
    type: 'danger',
    title: 'Safety Incident',
    message: 'Minor incident reported at Shopping Center project - Review required',
    date: '2024-01-19',
    read: false,
  },
  {
    id: 4,
    type: 'success',
    title: 'Milestone Achieved',
    message: 'Highway Expansion Project successfully completed ahead of schedule',
    date: '2024-01-15',
    read: true,
  },
];

export const documents = [
  {
    id: 1,
    name: 'Project Charter - Downtown Office.pdf',
    type: 'PDF',
    size: '2.4 MB',
    date: '2024-01-10',
    project: 'Downtown Office Complex',
  },
  {
    id: 2,
    name: 'Safety Plan - All Projects.docx',
    type: 'Document',
    size: '1.8 MB',
    date: '2024-01-08',
    project: 'General',
  },
  {
    id: 3,
    name: 'Budget Spreadsheet Q1.xlsx',
    type: 'Spreadsheet',
    size: '560 KB',
    date: '2024-01-15',
    project: 'General',
  },
  {
    id: 4,
    name: 'Site Photos - Week 3.zip',
    type: 'Archive',
    size: '45 MB',
    date: '2024-01-20',
    project: 'Residential Tower A',
  },
  {
    id: 5,
    name: 'Compliance Report.pdf',
    type: 'PDF',
    size: '3.2 MB',
    date: '2024-01-12',
    project: 'General',
  },
];

export const budgetData = [
  {
    project: 'Downtown Office Complex',
    budget: 2500000,
    spent: 1600000,
    remaining: 900000,
    percentage: 64,
  },
  {
    project: 'Residential Tower A',
    budget: 5200000,
    spent: 2200000,
    remaining: 3000000,
    percentage: 42,
  },
  {
    project: 'Shopping Center Renovation',
    budget: 1800000,
    spent: 270000,
    remaining: 1530000,
    percentage: 15,
  },
  {
    project: 'Highway Expansion Project',
    budget: 3500000,
    spent: 3400000,
    remaining: 100000,
    percentage: 97,
  },
  {
    project: 'Hospital Wing Extension',
    budget: 4100000,
    spent: 2400000,
    remaining: 1700000,
    percentage: 58,
  },
];

export const reportData = [
  {
    date: 'Jan 1',
    'In Progress': 10,
    Completed: 2,
    Planning: 2,
  },
  {
    date: 'Jan 5',
    'In Progress': 11,
    Completed: 2,
    Planning: 3,
  },
  {
    date: 'Jan 10',
    'In Progress': 11,
    Completed: 3,
    Planning: 2,
  },
  {
    date: 'Jan 15',
    'In Progress': 12,
    Completed: 3,
    Planning: 2,
  },
  {
    date: 'Jan 20',
    'In Progress': 12,
    Completed: 4,
    Planning: 1,
  },
];

export const tasks = [
  {
    id: 1,
    title: 'Foundation Excavation',
    project: 'Downtown Office Complex',
    assignedTo: 'John Doe',
    progress: 100,
    status: 'Completed',
    dueDate: '2024-12-15',
    priority: 'High',
    jobCount: 3,
  },
  {
    id: 2,
    title: 'Steel Frame Installation',
    project: 'Downtown Office Complex',
    assignedTo: 'Sarah Johnson',
    progress: 85,
    status: 'In Progress',
    dueDate: '2025-01-30',
    priority: 'High',
    jobCount: 5,
  },
  {
    id: 3,
    title: 'Concrete Pour - Floor 3',
    project: 'Residential Tower A',
    assignedTo: 'Mike Chen',
    progress: 60,
    status: 'In Progress',
    dueDate: '2025-02-10',
    priority: 'High',
    jobCount: 4,
  },
  {
    id: 4,
    title: 'Electrical Wiring - Phase 1',
    project: 'Residential Tower A',
    assignedTo: 'David Martinez',
    progress: 45,
    status: 'In Progress',
    dueDate: '2025-02-28',
    priority: 'Medium',
    jobCount: 6,
  },
  {
    id: 5,
    title: 'HVAC System Installation',
    project: 'Shopping Center Renovation',
    assignedTo: 'John Doe',
    progress: 20,
    status: 'Planning',
    dueDate: '2025-04-15',
    priority: 'Medium',
    jobCount: 2,
  },
  {
    id: 6,
    title: 'Demolition - East Wing',
    project: 'Shopping Center Renovation',
    assignedTo: 'Emma Williams',
    progress: 0,
    status: 'Planning',
    dueDate: '2025-03-01',
    priority: 'High',
    jobCount: 4,
  },
  {
    id: 7,
    title: 'Final Inspection',
    project: 'Highway Expansion Project',
    assignedTo: 'Sarah Johnson',
    progress: 100,
    status: 'Completed',
    dueDate: '2024-11-15',
    priority: 'High',
    jobCount: 2,
  },
  {
    id: 8,
    title: 'Medical Equipment Installation',
    project: 'Hospital Wing Extension',
    assignedTo: 'Mike Chen',
    progress: 35,
    status: 'In Progress',
    dueDate: '2025-03-20',
    priority: 'Medium',
    jobCount: 3,
  },
  {
    id: 9,
    title: 'Paint & Finishing - Level 2',
    project: 'Downtown Office Complex',
    assignedTo: 'David Martinez',
    progress: 40,
    status: 'In Progress',
    dueDate: '2025-03-10',
    priority: 'Low',
    jobCount: 5,
  },
  {
    id: 10,
    title: 'Safety Inspection',
    project: 'Hospital Wing Extension',
    assignedTo: 'John Doe',
    progress: 15,
    status: 'In Progress',
    dueDate: '2025-02-15',
    priority: 'High',
    jobCount: 3,
  },
];

export const jobs = [
  { id: 1, taskId: 1, name: 'Site Preparation', status: 'Completed', assignedTo: 'John Doe' },
  { id: 2, taskId: 1, name: 'Soil Testing', status: 'Completed', assignedTo: 'John Doe' },
  { id: 3, taskId: 1, name: 'Excavation Crew Briefing', status: 'Completed', assignedTo: 'John Doe' },
  { id: 4, taskId: 2, name: 'Beam Delivery', status: 'Completed', assignedTo: 'Sarah Johnson' },
  { id: 5, taskId: 2, name: 'Crane Setup', status: 'Completed', assignedTo: 'Sarah Johnson' },
  { id: 6, taskId: 2, name: 'Column Installation - North', status: 'In Progress', assignedTo: 'Sarah Johnson' },
  { id: 7, taskId: 2, name: 'Column Installation - South', status: 'In Progress', assignedTo: 'Sarah Johnson' },
  { id: 8, taskId: 2, name: 'Safety Verification', status: 'Planning', assignedTo: 'Sarah Johnson' },
  { id: 9, taskId: 3, name: 'Forms Setup', status: 'Completed', assignedTo: 'Mike Chen' },
  { id: 10, taskId: 3, name: 'Rebar Placement', status: 'Completed', assignedTo: 'Mike Chen' },
  { id: 11, taskId: 3, name: 'Concrete Mix Preparation', status: 'In Progress', assignedTo: 'Mike Chen' },
  { id: 12, taskId: 3, name: 'Concrete Pouring', status: 'In Progress', assignedTo: 'Mike Chen' },
  { id: 13, taskId: 4, name: 'Conduit Installation', status: 'In Progress', assignedTo: 'David Martinez' },
  { id: 14, taskId: 4, name: 'Wire Threading', status: 'In Progress', assignedTo: 'David Martinez' },
  { id: 15, taskId: 4, name: 'Panel Mounting', status: 'Planning', assignedTo: 'David Martinez' },
  { id: 16, taskId: 4, name: 'Circuit Testing', status: 'Planning', assignedTo: 'David Martinez' },
  { id: 17, taskId: 4, name: 'Final Inspection', status: 'Planning', assignedTo: 'David Martinez' },
  { id: 18, taskId: 4, name: 'Documentation', status: 'Planning', assignedTo: 'David Martinez' },
  { id: 19, taskId: 5, name: 'Ductwork Design Review', status: 'Planning', assignedTo: 'John Doe' },
  { id: 20, taskId: 5, name: 'Material Procurement', status: 'Planning', assignedTo: 'John Doe' },
  { id: 21, taskId: 6, name: 'East Wing Assessment', status: 'Planning', assignedTo: 'Emma Williams' },
  { id: 22, taskId: 6, name: 'Hazmat Inspection', status: 'Planning', assignedTo: 'Emma Williams' },
  { id: 23, taskId: 6, name: 'Debris Removal', status: 'Planning', assignedTo: 'Emma Williams' },
  { id: 24, taskId: 6, name: 'Structural Documentation', status: 'Planning', assignedTo: 'Emma Williams' },
  { id: 25, taskId: 7, name: 'Final Walk-through', status: 'Completed', assignedTo: 'Sarah Johnson' },
  { id: 26, taskId: 7, name: 'Documentation Review', status: 'Completed', assignedTo: 'Sarah Johnson' },
  { id: 27, taskId: 8, name: 'Equipment Delivery', status: 'In Progress', assignedTo: 'Mike Chen' },
  { id: 28, taskId: 8, name: 'Installation Setup', status: 'In Progress', assignedTo: 'Mike Chen' },
  { id: 29, taskId: 8, name: 'System Testing', status: 'Planning', assignedTo: 'Mike Chen' },
  { id: 30, taskId: 9, name: 'Surface Preparation', status: 'Completed', assignedTo: 'David Martinez' },
  { id: 31, taskId: 9, name: 'Primer Application', status: 'In Progress', assignedTo: 'David Martinez' },
  { id: 32, taskId: 9, name: 'Paint Application', status: 'In Progress', assignedTo: 'David Martinez' },
  { id: 33, taskId: 9, name: 'Trim & Finish', status: 'In Progress', assignedTo: 'David Martinez' },
  { id: 34, taskId: 9, name: 'Quality Check', status: 'Planning', assignedTo: 'David Martinez' },
  { id: 35, taskId: 10, name: 'Safety Protocols Review', status: 'In Progress', assignedTo: 'John Doe' },
  { id: 36, taskId: 10, name: 'Site Hazard Assessment', status: 'In Progress', assignedTo: 'John Doe' },
  { id: 37, taskId: 10, name: 'Compliance Verification', status: 'Planning', assignedTo: 'John Doe' },
];
